# Generated by Django 3.2.3 on 2021-05-23 18:21

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models

import frozen_data.fields
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlatModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_int", models.IntegerField()),
                ("field_str", models.TextField()),
                ("field_bool", models.BooleanField()),
                ("field_date", models.DateField()),
                ("field_decimal", models.DecimalField(decimal_places=3, max_digits=8)),
                ("field_datetime", models.DateTimeField()),
                ("field_float", models.FloatField()),
                ("field_uuid", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="NestedModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frozen",
                    frozen_data.fields.FrozenDataField(
                        tests.models.FlatModel,
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "current",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests.flatmodel",
                    ),
                ),
            ],
        ),
    ]
