# Generated by Django 3.2.4 on 2021-06-04 11:50

from django.db import migrations

import frozen_field.fields
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deepnestedmodel",
            name="frozen",
            field=frozen_field.fields.FrozenObjectField(
                "tests.NestedModel",
                blank=True,
                encoder=tests.models.CustomJSONEncoder,
                exclude=[],
                include=["id", "frozen"],
                null=True,
                select_related=[],
            ),
        ),
    ]
