# Generated by Django 3.2.3 on 2021-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flatmodel",
            name="field_json",
            field=models.JSONField(null=True),
        ),
    ]
