# Generated by Django 4.0.6 on 2022-07-07 14:34

import django.db.models.deletion
from django.db import migrations, models

import frozen_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line1", models.CharField(blank=True, max_length=100)),
                ("line2", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_address",
                    frozen_field.fields.FrozenObjectField(
                        "demo.Address",
                        converters={},
                        exclude=[],
                        include=[],
                        select_properties=[],
                        select_related=[],
                    ),
                ),
                (
                    "billing_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="demo.address"
                    ),
                ),
            ],
        ),
    ]
