# Generated by Django 4.0.6 on 2022-07-07 14:38

from django.db import migrations

import frozen_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_alter_order_delivery_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=frozen_field.fields.FrozenObjectField(
                "demo.Address",
                blank=True,
                converters={},
                exclude=[],
                include=[],
                null=True,
                select_properties=[],
                select_related=[],
            ),
        ),
    ]
